// src/AnimationCat.jsx
import React from 'react';
import styled, { keyframes } from 'styled-components';

const rotate = keyframes`
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
`;

const RotatingCat = styled.img`
  animation: ${rotate} 2s linear infinite;
  position: absolute;
  top: 10px;
  right: 20px;
`;

export default () => (
  <RotatingCat 
    src="/rotatingCat.png"
    height="150"
    width="150"
  />
);

// Vue/project/src/components/AnimationCat.vue
<template>
<div>
  <SRotatingCat
    src="../../static/rotatingCat.png"
    height="150"
    width="150"
  />
</div>
</template>

<script>
import styled, { keyframes } from 'vue-styled-components';

const rotate = keyframes`
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
`;

const SRotatingCat = styled.img`
  animation: ${rotate} 2s linear infinite;
  position: absolute;
  top: 10px;
  right: 30px;
`;

export default {
  name: 'AnimationCat',

  components: {
    SRotatingCat,
  },
};
</script>
